### ISSUE TITLE
java.lang.NoSuchFieldException: No field sDurationScale in class Landroid/animation/ValueAnimator;

### ISSUE THREAD

**Issue by maxakash** [Moriafly/LyricViewX#3]
While updating the time, I am getting the following error.
```
W/System.err: java.lang.NoSuchFieldException: No field sDurationScale in class Landroid/animation/ValueAnimator; (declaration of 'android.animation.ValueAnimator' appears in /system/framework/framework.jar)
2021-05-30 13:28:07.076 23033-23033/com.speechify.musicplayer W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
2021-05-30 13:28:07.077 23033-23033/com.speechify.musicplayer W/System.err:     at com.dirror.lyricviewx.LyricUtil.resetDurationScale(LyricUtil.kt:192)
2021-05-30 13:28:07.078 23033-23033/com.speechify.musicplayer W/System.err:     at com.dirror.lyricviewx.LyricViewX.smoothScrollTo(LyricViewX.kt:412)
2021-05-30 13:28:07.078 23033-23033/com.speechify.musicplayer W/System.err:     at com.dirror.lyricviewx.LyricViewX.smoothScrollTo$default(LyricViewX.kt:402)
2021-05-30 13:28:07.079 23033-23033/com.speechify.musicplayer W/System.err:     at com.dirror.lyricviewx.LyricViewX$updateTime$1.run(LyricViewX.kt:615)
2021-05-30 13:28:07.079 23033-23033/com.speechify.musicplayer W/System.err:     at com.dirror.lyricviewx.LyricViewX.runOnUi(LyricViewX.kt:489)
2021-05-30 13:28:07.080 23033-23033/com.speechify.musicplayer W/System.err:     at com.dirror.lyricviewx.LyricViewX.updateTime(LyricViewX.kt:609)
2021-05-30 13:28:07.080 23033-23033/com.speechify.musicplayer W/System.err:     at com.speechify.musicplayer.views.LyricsFragment$updateSliderPosition$1.invokeSuspend(LyricsFragment.kt:77)
2021-05-30 13:28:07.081 23033-23033/com.speechify.musicplayer W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-05-30 13:28:07.081 23033-23033/com.speechify.musicplayer W/System.err:     at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
2021-05-30 13:28:07.082 23033-23033/com.speechify.musicplayer W/System.err:     at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
2021-05-30 13:28:07.082 23033-23033/com.speechify.musicplayer W/System.err:     at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:398)
2021-05-30 13:28:07.083 23033-23033/com.speechify.musicplayer W/System.err:     at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:432)
2021-05-30 13:28:07.083 23033-23033/com.speechify.musicplayer W/System.err:     at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:421)
2021-05-30 13:28:07.084 23033-23033/com.speechify.musicplayer W/System.err:     at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:519)
2021-05-30 13:28:07.084 23033-23033/com.speechify.musicplayer W/System.err:     at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
2021-05-30 13:28:07.085 23033-23033/com.speechify.musicplayer W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2021-05-30 13:28:07.085 23033-23033/com.speechify.musicplayer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-05-30 13:28:07.086 23033-23033/com.speechify.musicplayer W/System.err:     at android.os.Looper.loop(Looper.java:223)
2021-05-30 13:28:07.086 23033-23033/com.speechify.musicplayer W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7660)
2021-05-30 13:28:07.087 23033-23033/com.speechify.musicplayer W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-05-30 13:28:07.087 23033-23033/com.speechify.musicplayer W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2021-05-30 13:28:07.088 23033-23033/com.speechify.musicplayer W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-05-30 13:28:12.106 23033-23033/com.speechify.musicplayer W/ify.musicplaye: Accessing hidden field Landroid/animation/ValueAnimator;->sDurationScale:F (greylist-max-p, reflection, denied)
```

Here is my code I am using to update the lyrics time

```
  private fun updateSliderPosition() {
        updateSliderJob = lifecycleScope.launch {

            while (true) {
                binding.lyricView.updateTime(MusicPlayerController.getCurrentPosition().toLong())
                delay(1000)
            }
        }
    }
```

**Comment by Moriafly** [comment]
This is a bug
ValueAnimator has a private variable: sdurationScale
Because some users will adjust the length of the system animation in the developer options, the time recovery animation is not as expected.I change it in code by reflection, which is probably not a good way to do it.
I'm going to solve the problem in other ways.

**Comment by maxakash** [comment]
Will removing the function causing this bug have any impact?

**Comment by Moriafly** [comment]
It might cause the animation to get out of whack, but I found a way around it. (u‿ฺu✿ฺ)

**Comment by maxakash** [comment]
Will you release a new version ?

**Comment by Moriafly** [comment]
Yes, I will release a new version in the next few days.

**Comment by maxakash** [comment]
I need to submit my project tomorrow.
Can you please share the workaround.


Thanks

**Comment by Moriafly** [comment]
I'll release a beta version later, you can try it out.

**Comment by maxakash** [comment]
Thanks. Waiting for it.

**Comment by Moriafly** [comment]
1.2.0-beta01 has just been released.
```
    implementation 'com.github.Moriafly:LyricViewX:1.2.0-beta01'
```
You can try it

**Comment by maxakash** [comment]
I have updated to 1.2.0-beta01. Everythings is working fine but logcat is throwing the below errors.
Please look into it.

![Screenshot 2021-05-30 at 6 25 55 PM](https://user-images.githubusercontent.com/17406944/120104941-806e2000-c174-11eb-8288-2717d9ad35a8.png)

**Comment by Moriafly** [comment]
I'm very sorry. This is my test log and I forgot to delete it. It does not affect the normal use.I will remove it later in the beta02 release.

**Comment by maxakash** [comment]
Can you please remove it now because I need to sumbit my project and HR will see it as a bug?

**Comment by Moriafly** [comment]
The 1.2.0-beta02 has just been released to fix this problem.

**Comment by maxakash** [comment]
Everything seems to work fine. Thanks for your help @Moriafly

**Comment by Moriafly** [comment]
You're welcome. Wish you all the best.
